version: "3.9"

services:
  web:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always

volumes:
  postgres_data:
